### ISSUE TITLE
Emoji in text fields

### ISSUE THREAD

**Issue by kwillno** [Nabla-NTNU/jubside#11]
If emoji are entered in any markdown text field on the admin page and the changes are saved, no data is saved and the server responds with 500.   
  
Tested in the `Arrangement` type in the textboxes `Ingress` and `Brødtekst`.  
Errors in other fields return an error while saving the data.

**Comment by Amund211** [comment]
Looks like it's this same issue from 2 years ago https://github.com/Nabla-NTNU/nablaweb/issues/379

**Comment by Amund211** [comment]
Fixed :blush:
